var GeneratedItemEnum = {
  STAR: 0,
  AMMO: 1,
  SPEEDUP: 2
};

//This class represents item generated by generator
//Right now, only two items are available - ammo and stars
GeneratedItem = function(type, x, y) {
    this.itemType = type;

    Phaser.Sprite.call(this, game, x, y, this.getSpriteKey(this.itemType));
    game.physics.enable(this, Phaser.Physics.ARCADE);
    this.body.allowGravity = false;
    this.anchor.setTo(0.5);

    if (this.itemType == GeneratedItemEnum.AMMO) {
      this.scale.set(0.5);
    }

    //for the object pool
    this.kill();
};

GeneratedItem.prototype = Object.create(Phaser.Sprite.prototype);
GeneratedItem.prototype.constructor = GeneratedItem;

GeneratedItem.prototype.getSpriteKey = function(type) {
  if (type == GeneratedItemEnum.STAR)
    return KEY_SPRITE_STAR;

  return KEY_SPRITE_AMMO;
}

//always spawn item above from the camera
GeneratedItem.prototype.spawnItem = function() {
  this.x = game.math.random(0, game.world.width);
  this.y = game.camera.y - 50;
}

GeneratedItem.prototype.killItem = function() {
  this.kill();
}
